spring:
  application:
    name: monthly-control
  jpa: 
    properties:
      hibernate:
        formatSql: true
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    active: test
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
default:
  sender: ${DEFAULT_EMAIL_SENDER}
admin:
  email: ${ADMIN_EMAIL}
  pass: ${ADMIN_PASS}
